from __future__ import annotations

from copy import deepcopy
from typing import Any

SCHEMA_VERSION = "0.10.1"
LEGACY_SCHEMA_VERSION = "0.9.0"
# Validators accept every accepted version during the migration window;
# emitters always write SCHEMA_VERSION (see docs/schema-0.10.1-design.md §7).
ACCEPTED_SCHEMA_VERSIONS = frozenset({LEGACY_SCHEMA_VERSION, SCHEMA_VERSION})
SCHEMA_VERSIONS_ENUM = [LEGACY_SCHEMA_VERSION, SCHEMA_VERSION]
SCHEMA_ID = "https://spec.starintel.actor/schema/starintel-doc-v0.10.1.json"
SCHEMA_REVISION = "0.10.1+fields.20260919.1"


def string(*, enum: list[str] | None = None, pattern: str | None = None) -> dict[str, Any]:
    out: dict[str, Any] = {"type": "string"}
    if enum is not None:
        out["enum"] = enum
    if pattern is not None:
        out["pattern"] = pattern
    return out


def number(*, minimum: float | None = None, maximum: float | None = None) -> dict[str, Any]:
    out: dict[str, Any] = {"type": "number"}
    if minimum is not None:
        out["minimum"] = minimum
    if maximum is not None:
        out["maximum"] = maximum
    return out


def integer(*, minimum: int | None = None) -> dict[str, Any]:
    out: dict[str, Any] = {"type": "integer"}
    if minimum is not None:
        out["minimum"] = minimum
    return out


def boolean() -> dict[str, Any]:
    return {"type": "boolean"}


def array(items: dict[str, Any]) -> dict[str, Any]:
    return {"type": "array", "items": items}


def obj(
    properties: dict[str, Any],
    *,
    required: tuple[str, ...] = (),
    additional: bool | dict[str, Any] = False,
) -> dict[str, Any]:
    out: dict[str, Any] = {
        "type": "object",
        "properties": properties,
        "additionalProperties": additional,
    }
    if required:
        out["required"] = list(required)
    return out


STR = string()
STRS = array(STR)
NUM = number()
BOOL = boolean()
INT = integer()
SCORE = number(minimum=0.0, maximum=1.0)
DATE_TIME = {"type": "string", "format": "date-time"}
NULLABLE_DATE_TIME = {"anyOf": [DATE_TIME, {"type": "null"}]}
NULLABLE_STRING = {"anyOf": [STR, {"type": "null"}]}
JSON_VALUE: dict[str, Any] = {}
JSON_MAP = {"type": "object", "additionalProperties": True}

IDENTIFIER = obj(
    {
        "scheme": STR,
        "value": STR,
        "issuer": STR,
        "jurisdiction": STR,
        "canonical": BOOL,
        "confidence": SCORE,
        "valid_from": NULLABLE_DATE_TIME,
        "valid_to": NULLABLE_DATE_TIME,
        "url": STR,
        "notes": STR,
    },
    required=("scheme", "value"),
)

# Monetary record absorbed from the retired 0.9 expansion registry
# (field_kinds.money). Kept unrequired so partial observations stay valid.
MONEY = obj(
    {
        "amount": NUM,
        "currency": STR,
        "basis": STR,
        "as_of": NULLABLE_DATE_TIME,
        "notes": STR,
    }
)

SOURCE = obj(
    {
        "source_id": STR,
        "kind": STR,
        "type": STR,
        "sensor": STR,
        "name": STR,
        "title": STR,
        "publisher": STR,
        "author": STR,
        "organization": STR,
        "uri": STR,
        "url": STR,
        "archive_url": STR,
        "published_at": NULLABLE_DATE_TIME,
        "retrieved_at": NULLABLE_DATE_TIME,
        "accessed_at": NULLABLE_DATE_TIME,
        "language": STR,
        "jurisdiction": STR,
        "medium": STR,
        "credibility": SCORE,
        "reliability": SCORE,
        "authenticity": SCORE,
        "independence": SCORE,
        "access_method": STR,
        "query": STR,
        "request_id": STR,
        "response_status": INT,
        "content_hash": STR,
        "hash_algorithm": STR,
        "license": STR,
        "quote": STR,
        "locator": STR,
        "page": STR,
        "section": STR,
        "notes": STR,
        "metadata": JSON_MAP,
    }
)

EVIDENCE = obj(
    {
        "evidence_id": STR,
        "source_id": STR,
        "source_url": STR,
        "kind": STR,
        "role": STR,
        "claim": STR,
        "observation": STR,
        "excerpt": STR,
        "locator": STR,
        "page": STR,
        "section": STR,
        "collected_at": NULLABLE_DATE_TIME,
        "observed_at": NULLABLE_DATE_TIME,
        "valid_from": NULLABLE_DATE_TIME,
        "valid_to": NULLABLE_DATE_TIME,
        "content_hash": STR,
        "hash_algorithm": STR,
        "confidence": SCORE,
        "corroborates": STRS,
        "contradicts": STRS,
        "chain_of_custody": STRS,
        "attachments": STRS,
        "status": STR,
        "notes": STR,
        "metadata": JSON_MAP,
    }
)

TEMPORAL = obj(
    {
        "observed_at": NULLABLE_DATE_TIME,
        "collected_at": NULLABLE_DATE_TIME,
        "published_at": NULLABLE_DATE_TIME,
        "created_at": NULLABLE_DATE_TIME,
        "modified_at": NULLABLE_DATE_TIME,
        "event_start": NULLABLE_DATE_TIME,
        "event_end": NULLABLE_DATE_TIME,
        "valid_from": NULLABLE_DATE_TIME,
        "valid_to": NULLABLE_DATE_TIME,
        "first_seen": NULLABLE_DATE_TIME,
        "last_seen": NULLABLE_DATE_TIME,
        "timezone": STR,
        "precision": STR,
        "recurrence": STR,
        "duration_seconds": NUM,
        "sequence": INT,
        "notes": STR,
    }
)

PROVENANCE = obj(
    {
        "collector": STR,
        "collector_type": STR,
        "agent": STR,
        "actor": STR,
        "skill": STR,
        "tool": STR,
        "model": STR,
        "prompt_hash": STR,
        "run_id": STR,
        "session_id": STR,
        "operation_id": STR,
        "method": STR,
        "pipeline": STR,
        "imported_from": STR,
        "original_id": STR,
        "original_schema_version": STR,
        "original_path": STR,
        "transform": STR,
        "software_version": STR,
        "environment": STR,
        "created_by": STR,
        "updated_by": STR,
        "notes": STR,
        "metadata": JSON_MAP,
    }
)

ASSESSMENT = obj(
    {
        "confidence": SCORE,
        "analytic_confidence": SCORE,
        "source_reliability": SCORE,
        "information_credibility": SCORE,
        "relevance": SCORE,
        "priority": SCORE,
        "threat": SCORE,
        "impact": SCORE,
        "likelihood": SCORE,
        "severity": SCORE,
        "deception_probability": SCORE,
        "uncertainty": SCORE,
        "bias": SCORE,
        "completeness": SCORE,
        "assumptions": STRS,
        "inferences": STRS,
        "alternatives": STRS,
        "counterevidence": STRS,
        "gaps": STRS,
        "caveats": STRS,
        "criteria": JSON_MAP,
        "scores": {"type": "object", "additionalProperties": NUM},
        "notes": STR,
    }
)

VERIFICATION = obj(
    {
        "status": STR,
        "result": STR,
        "verified": BOOL,
        "verified_by": STRS,
        "verified_at": NULLABLE_DATE_TIME,
        "methods": STRS,
        "checks": STRS,
        "conflicts": STRS,
        "unresolved": STRS,
        "last_reviewed_at": NULLABLE_DATE_TIME,
        "review_due_at": NULLABLE_DATE_TIME,
        "review_count": INT,
        "notes": STR,
    }
)

HANDLING = obj(
    {
        "visibility": STR,
        "handling": STR,
        "classification": STR,
        "compartment": STR,
        "dissemination": STRS,
        "access_groups": STRS,
        "caveats": STRS,
        "retention": STR,
        "embargo_until": NULLABLE_DATE_TIME,
        "pii": BOOL,
        "sensitive": BOOL,
        "redactions": STRS,
        "license": STR,
        "copyright": STR,
        "notes": STR,
    }
)

LINEAGE = obj(
    {
        "parent_ids": STRS,
        "child_ids": STRS,
        "derived_from": STRS,
        "source_document_ids": STRS,
        "supersedes": STRS,
        "superseded_by": STRS,
        "merged_from": STRS,
        "split_from": STRS,
        "duplicates": STRS,
        "replaces": STRS,
        "migration_from": STR,
        "migration_notes": STRS,
        "transform": STR,
        "generation": INT,
    }
)

QUALITY = obj(
    {
        "completeness": SCORE,
        "consistency": SCORE,
        "timeliness": SCORE,
        "uniqueness": SCORE,
        "accuracy": SCORE,
        "coverage": SCORE,
        "freshness": SCORE,
        "validation_status": STR,
        "validation_errors": STRS,
        "warnings": STRS,
        "missing_fields": STRS,
        "last_validated_at": NULLABLE_DATE_TIME,
        "validator": STR,
    }
)

WORKFLOW = obj(
    {
        "research_status": STR,
        "queue": STR,
        "priority": NUM,
        "assigned_to": STRS,
        "requested_by": STR,
        "due_at": NULLABLE_DATE_TIME,
        "next_action": STR,
        "blockers": STRS,
        "run_id": STR,
        "actor": STR,
        "skill": STR,
        "recursion_depth": INT,
        "max_depth": INT,
        "root_target_id": STR,
        "selected_from": STRS,
        "selection_reason": STRS,
        "selection_score": NUM,
        "selection_features": JSON_MAP,
        "completed_at": NULLABLE_DATE_TIME,
        "notes": STR,
    }
)

GEOSPATIAL = obj(
    {
        "lat": NUM,
        "lon": NUM,
        "long": NUM,
        "altitude": NUM,
        "accuracy_meters": NUM,
        "bbox": array(NUM),
        "geohash": STR,
        "coordinate_system": STR,
        "place_name": STR,
        "address_id": STR,
        "street": STR,
        "street2": STR,
        "city": STR,
        "county": STR,
        "state": STR,
        "region": STR,
        "postal": STR,
        "country": STR,
        "country_code": STR,
        "timezone": STR,
        "jurisdiction": STR,
        "notes": STR,
    }
)

ATTACHMENT = obj(
    {
        "attachment_id": STR,
        "name": STR,
        "role": STR,
        "description": STR,
        "media_type": STR,
        "uri": STR,
        "size_bytes": INT,
        "content_hash": STR,
        "hash_algorithm": STR,
        "captured_at": NULLABLE_DATE_TIME,
        "created_at": NULLABLE_DATE_TIME,
        "metadata": JSON_MAP,
    }
)

RELATION_ENDPOINT = obj(
    {
        "id": STR,
        "entity_id": STR,
        "document_id": STR,
        "external_id": STR,
        "dtype": STR,
        "label": STR,
        "name": STR,
        "role": STR,
        "unresolved": BOOL,
        "external_ids": array(IDENTIFIER),
        "aliases": STRS,
        "qualifiers": JSON_MAP,
        "metadata": JSON_MAP,
    }
)


ENTITY_FIELDS = {
    "etype": STR,
    "eid": STR,
    "name": STR,
    "display_name": STR,
    "legal_name": STR,
    "short_name": STR,
    "former_names": STRS,
    "description": STR,
    "bio": STR,
    "jurisdiction": STR,
    "country": STR,
    "status": STR,
    "founded_at": NULLABLE_DATE_TIME,
    "dissolved_at": NULLABLE_DATE_TIME,
    "website": STR,
    "image_url": STR,
    "logo_url": STR,
    "external_ids": array(IDENTIFIER),
    "contact_ids": STRS,
    "location_ids": STRS,
}

PERSON_FIELDS = {
    **ENTITY_FIELDS,
    "fname": STR,
    "mname": STR,
    "lname": STR,
    "suffix": STR,
    "full_name": STR,
    "preferred_name": STR,
    "gender": STR,
    "pronouns": STR,
    "dob": NULLABLE_DATE_TIME,
    "birthplace": STR,
    "death_date": NULLABLE_DATE_TIME,
    "nationalities": STRS,
    "citizenships": STRS,
    "occupations": STRS,
    "employers": STRS,
    "positions": STRS,
    "education_ids": STRS,
    "social_account_ids": STRS,
    "email_ids": STRS,
    "phone_ids": STRS,
    "family_ids": STRS,
    "associate_ids": STRS,
    "political_affiliations": STRS,
    "professional_affiliations": STRS,
    "public_roles": STRS,
    "misc": STRS,
}

ORG_FIELDS = {
    **ENTITY_FIELDS,
    "org_type": STR,
    "registration_number": STR,
    "reg": STR,
    "tax_id": STR,
    "lei": STR,
    "ticker": STR,
    "exchange": STR,
    "industry": STR,
    "sectors": STRS,
    "mission": STR,
    "business": STR,
    "headquarters": STR,
    "parent_id": STR,
    "subsidiary_ids": STRS,
    "affiliate_ids": STRS,
    "predecessor_ids": STRS,
    "successor_ids": STRS,
    "owner_ids": STRS,
    "beneficial_owner_ids": STRS,
    "director_ids": STRS,
    "executive_ids": STRS,
    "member_ids": STRS,
    "employee_count": INT,
    "revenue": NUM,
    "currency": STR,
    "fiscal_year_end": STR,
    "products": STRS,
    "services": STRS,
    "markets": STRS,
    "government_levels": STRS,
}

RELATION_FIELDS = {
    "subject": {"anyOf": [STR, RELATION_ENDPOINT]},
    "predicate": STR,
    "object": {"anyOf": [STR, RELATION_ENDPOINT, array(STR), array(RELATION_ENDPOINT)]},
    "source": STR,
    "target": STR,
    "directed": BOOL,
    "inverse_predicate": STR,
    "relation_type": STR,
    "qualifiers": JSON_MAP,
    "weight": NUM,
    "confidence": SCORE,
    "start_at": NULLABLE_DATE_TIME,
    "end_at": NULLABLE_DATE_TIME,
    "active": BOOL,
    "note": STR,
}

TARGET_FIELDS = {
    "actor": STR,
    "target": STR,
    "target_id": STR,
    "target_type": STR,
    "query": STR,
    "research_question": STR,
    "hypotheses": STRS,
    "objectives": STRS,
    "in_scope": STRS,
    "out_of_scope": STRS,
    "scope_type": STR,
    "seed_ids": STRS,
    "source_ids": STRS,
    "required_dtypes": STRS,
    "preferred_sources": STRS,
    "excluded_sources": STRS,
    "delay": INT,
    "recurring": BOOL,
    "recurrence": STR,
    "options": array(JSON_VALUE),
    "depth": INT,
    "max_depth": INT,
    "breadth": INT,
    "priority": NUM,
    "score": NUM,
    "selection_reason": STRS,
    "status": STR,
    "next_run_at": NULLABLE_DATE_TIME,
}

# Shared device-class vocabulary, anchored to the nmap-os-db device classes
# (docs/schema-0.10.1-design.md §5.1). Free-string host.device_type remains
# for legacy data.
DEVICE_CLASS_VALUES = [
    "other",
    "unknown",
    "general-purpose",
    "router",
    "broadband-router",
    "switch",
    "wap",
    "bridge",
    "firewall",
    "load-balancer",
    "proxy-server",
    "print-server",
    "terminal-server",
    "terminal",
    "phone",
    "voip-phone",
    "voip-adapter",
    "pbx",
    "webcam",
    "printer",
    "media-device",
    "game-console",
    "pda",
    "storage",
    "storage-misc",
    "power-device",
    "remote-management",
    "security-misc",
    "specialized",
    "telecom-misc",
    "iot",
]

# ENTITY-MIB PhysicalClass-anchored hardware taxonomy for network-device.
HARDWARE_CLASS_VALUES = [
    "unknown",
    "chassis",
    "backplane",
    "container",
    "power-supply",
    "fan",
    "sensor",
    "module",
    "port",
    "stack",
    "cpu",
    "energy-object",
    "battery",
    "storage-drive",
    "other",
]

HOST_FIELDS = {
    "hostname": STR,
    "fqdn": STR,
    "ip": STR,
    "ipv4": STRS,
    "ipv6": STRS,
    "mac": STR,
    "asn": INT,
    "organization": STR,
    "network_id": STR,
    "domain_ids": STRS,
    "reverse_dns": STRS,
    "os": STR,
    "os_version": STR,
    "architecture": STR,
    "device_type": STR,
    "device_class": string(enum=list(DEVICE_CLASS_VALUES)),
    "device_class_source": STR,
    "device_class_evidence": STR,
    "vendor": STR,
    "model": STR,
    "host_type": STR,
    "services": array(JSON_MAP),
    "ports": array(JSON_MAP),
    "certificates": array(JSON_MAP),
    "interface_records": array(JSON_MAP),
    "service_records": array(JSON_MAP),
    "certificate_records": array(JSON_MAP),
    "software_ids": STRS,
    "cloud_account_ids": STRS,
    "virtualization_type": STR,
    "parent_host_id": STR,
    "observed_by_ids": STRS,
    "technologies": STRS,
    "vulnerabilities": STRS,
    "first_seen": NULLABLE_DATE_TIME,
    "last_seen": NULLABLE_DATE_TIME,
}

DOMAIN_FIELDS = {
    "domain": STR,
    "record_type": STR,
    "record": STR,
    "resolved_addresses": STRS,
    "registrar": STR,
    "registrant": STR,
    "created_at": NULLABLE_DATE_TIME,
    "expires_at": NULLABLE_DATE_TIME,
    "updated_at": NULLABLE_DATE_TIME,
    "nameservers": STRS,
    "dns_records": array(JSON_MAP),
    "subdomains": STRS,
    "whois": JSON_MAP,
    "status": STRS,
    "dnssec": BOOL,
}

NETWORK_FIELDS = {
    "org": STR,
    "asn": INT,
    "asn_name": STR,
    "subnet": STR,
    "cidr": STR,
    "range_start": STR,
    "range_end": STR,
    "rir": STR,
    "country": STR,
    "description": STR,
    "network_type": STR,
    "prefixes": STRS,
    "allocation_id": STR,
    "registrant_id": STR,
    "contact_ids": STRS,
    "route_objects": STRS,
    "routing_policy": STRS,
    "bgp_observation_ids": STRS,
    "announced_by_asns": array(INT),
    "rpki_status": STR,
    "peer_asns": array(INT),
    "upstream_asns": array(INT),
    "downstream_asns": array(INT),
}

URL_FIELDS = {
    "url": STR,
    "scheme": STR,
    "host": STR,
    "port": INT,
    "path": STR,
    "query": STR,
    "fragment": STR,
    "title": STR,
    "content": STR,
    "content_type": STR,
    "status_code": INT,
    "headers": JSON_MAP,
    "redirect_chain": STRS,
    "links": STRS,
    "forms": array(JSON_MAP),
    "technologies": STRS,
    "content_hash": STR,
    "captured_at": NULLABLE_DATE_TIME,
}

LOCATION_FIELDS = {
    "name": STR,
    "location_type": STR,
    "address": STR,
    "street": STR,
    "street2": STR,
    "city": STR,
    "county": STR,
    "state": STR,
    "region": STR,
    "postal": STR,
    "country": STR,
    "country_code": STR,
    "lat": NUM,
    "long": NUM,
    "lon": NUM,
    "alt": NUM,
    "timezone": STR,
    "geohash": STR,
    "parent_location_id": STR,
    "contained_location_ids": STRS,
}

CONTACT_FIELDS = {
    "value": STR,
    "type": STR,
    "label": STR,
    "owner_id": STR,
    "status": STR,
    "verified": BOOL,
    "verified_at": NULLABLE_DATE_TIME,
    "first_seen": NULLABLE_DATE_TIME,
    "last_seen": NULLABLE_DATE_TIME,
}

MESSAGE_FIELDS = {
    "content": STR,
    "platform": STR,
    "user": STR,
    "user_id": STR,
    "is_reply": BOOL,
    "media": STRS,
    "message_id": STR,
    "reply_to": STR,
    "group": STR,
    "channel": STR,
    "thread_id": STR,
    "mentions": STRS,
    "reactions": array(JSON_MAP),
    "links": STRS,
    "posted_at": NULLABLE_DATE_TIME,
    "edited_at": NULLABLE_DATE_TIME,
    "deleted": BOOL,
    "visibility": STR,
}

POST_FIELDS = {
    **MESSAGE_FIELDS,
    "replies": array(JSON_MAP),
    "reply_count": INT,
    "repost_count": INT,
    "like_count": INT,
    "view_count": INT,
    "url": STR,
    "tags": STRS,
    "title": STR,
    "quote_post_id": STR,
}

EVENT_FIELDS = {
    "event_kind": STR,
    "name": STR,
    "description": STR,
    "participant_ids": STRS,
    "participants": STRS,
    "organizer_ids": STRS,
    "sponsor_ids": STRS,
    "location_ids": STRS,
    "start_at": NULLABLE_DATE_TIME,
    "end_at": NULLABLE_DATE_TIME,
    "status": STR,
    "outcome": STR,
    "agenda": STRS,
    "decisions": STRS,
    "actions": STRS,
    "amount": NUM,
    "currency": STR,
    "jurisdiction": STR,
    "case_id": STR,
    "contract_id": STR,
    "meeting_id": STR,
}

CLAIM_FIELDS = {
    "claim": STR,
    "claimant_id": STR,
    "subject_ids": STRS,
    "predicate": STR,
    "object": JSON_VALUE,
    "claim_type": STR,
    "polarity": STR,
    "certainty": SCORE,
    "supporting_evidence_ids": STRS,
    "contradicting_evidence_ids": STRS,
    "status": STR,
    "adjudication": STR,
}

ANALYSIS_FIELDS = {
    "question": STR,
    "method": STR,
    "framework": STR,
    "scope": STR,
    "input_ids": STRS,
    "finding_ids": STRS,
    "findings": STRS,
    "conclusions": STRS,
    "recommendations": STRS,
    "counterarguments": STRS,
    "limitations": STRS,
    "unresolved": STRS,
    "confidence": SCORE,
}

PRODUCT_FIELDS = {
    **ENTITY_FIELDS,
    "manufacturer_id": STR,
    "vendor_ids": STRS,
    "product_type": STR,
    "model": STR,
    "version_name": STR,
    "release_date": NULLABLE_DATE_TIME,
    "end_of_life": NULLABLE_DATE_TIME,
    "features": STRS,
    "capabilities": STRS,
    "integrations": STRS,
    "customers": STRS,
    "license": STR,
    "pricing": JSON_MAP,
    "technical": JSON_MAP,
}

FINANCIAL_FIELDS = {
    "entity_id": STR,
    "observation_type": STR,
    "amount": NUM,
    "currency": STR,
    "value_type": STR,
    "period_start": NULLABLE_DATE_TIME,
    "period_end": NULLABLE_DATE_TIME,
    "fiscal_year": INT,
    "fiscal_quarter": STR,
    "reported_at": NULLABLE_DATE_TIME,
    "counterparty_ids": STRS,
    "instrument": STR,
    "units": NUM,
    "unit_price": NUM,
    "percentage": NUM,
    "methodology": STR,
    "qualifications": STRS,
}

CONTRACT_FIELDS = {
    "contract_id": STR,
    "award_id": STR,
    "solicitation_id": STR,
    "vehicle_id": STR,
    "buyer_id": STR,
    "seller_id": STR,
    "agency_ids": STRS,
    "vendor_ids": STRS,
    "subcontractor_ids": STRS,
    "description": STR,
    "scope": STR,
    "award_type": STR,
    "competition_type": STR,
    "status": STR,
    "signed_at": NULLABLE_DATE_TIME,
    "start_at": NULLABLE_DATE_TIME,
    "end_at": NULLABLE_DATE_TIME,
    "ceiling_amount": NUM,
    "potential_amount": NUM,
    "obligated_amount": NUM,
    "outlay_amount": NUM,
    "recognized_revenue": NUM,
    "currency": STR,
    "naics": STRS,
    "psc": STRS,
    "place_of_performance": STR,
    "modifications": array(JSON_MAP),
}

LOBBYING_FIELDS = {
    "filing_id": STR,
    "registrant_id": STR,
    "client_id": STR,
    "lobbyist_ids": STRS,
    "government_entities": STRS,
    "issues": STRS,
    "specific_issues": STRS,
    "income": NUM,
    "expenses": NUM,
    "currency": STR,
    "period_start": NULLABLE_DATE_TIME,
    "period_end": NULLABLE_DATE_TIME,
    "filed_at": NULLABLE_DATE_TIME,
    "filing_type": STR,
    "amendment": BOOL,
    "termination": BOOL,
}

LEGAL_FIELDS = {
    "case_number": STR,
    "case_name": STR,
    "court": STR,
    "jurisdiction": STR,
    "judge_ids": STRS,
    "party_ids": STRS,
    "plaintiff_ids": STRS,
    "defendant_ids": STRS,
    "attorney_ids": STRS,
    "case_type": STR,
    "claims": STRS,
    "status": STR,
    "filed_at": NULLABLE_DATE_TIME,
    "closed_at": NULLABLE_DATE_TIME,
    "docket_entries": array(JSON_MAP),
    "outcome": STR,
    "citation": STR,
}

RESEARCH_PASS_FIELDS = {
    "research_question": STR,
    "method": STR,
    "classification_rules": STRS,
    "finding_ids": STRS,
    "findings": array(JSON_MAP),
    "supporting_record_ids": STRS,
    "counterevidence_ids": STRS,
    "unresolved_target_ids": STRS,
    "source_ids": STRS,
    "agent_identity": STR,
    "narrative_role": STR,
    "started_at": NULLABLE_DATE_TIME,
    "completed_at": NULLABLE_DATE_TIME,
    "iteration": INT,
}


RESEARCH_NODE_LIMITS = obj(
    {
        "max_depth": integer(minimum=1),
        "max_actor_runs": integer(minimum=1),
        "max_requests": integer(minimum=1),
        "max_elapsed_ms": integer(minimum=1),
        "max_repeated_state": integer(minimum=1),
        "max_cost": number(minimum=0.0),
        "currency": STR,
    }
)

RESEARCH_NODE_STOP = obj(
    {
        "when_actor_queue_empty": BOOL,
        "when_no_new_documents": BOOL,
        "when_objective_satisfied": BOOL,
        "halt_on_actor_failure": BOOL,
    }
)

RESEARCH_NODE_COUNTERS = obj(
    {
        "depth": integer(minimum=0),
        "actor_runs": integer(minimum=0),
        "requests": integer(minimum=0),
        "repeated_state": integer(minimum=0),
        "elapsed_ms": integer(minimum=0),
        "cost": number(minimum=0.0),
    }
)

RESEARCH_NODE_HISTORY_ENTRY = obj(
    {
        "from": NULLABLE_STRING,
        "to": STR,
        "at": DATE_TIME,
        "message": STR,
        "error": STR,
        "actor_id": STR,
        "run_id": STR,
        "output_ids": STRS,
        "artifact_ids": STRS,
    },
    required=("to", "at"),
)

RESEARCH_NODE_FIELDS = {
    "objective": STR,
    "instructions": STR,
    "status": string(
        enum=[
            "draft",
            "queued",
            "running",
            "paused",
            "blocked",
            "completed",
            "failed",
            "killed",
        ]
    ),
    "input_ids": STRS,
    "target_ids": STRS,
    "actor_ids": STRS,
    "actor_selection_rules": array(JSON_MAP),
    "output_ids": STRS,
    "artifact_ids": STRS,
    "child_ids": STRS,
    "dependency_ids": STRS,
    "run_ids": STRS,
    "current_actor_id": STR,
    "current_run_id": STR,
    "limits": RESEARCH_NODE_LIMITS,
    "stop": RESEARCH_NODE_STOP,
    "counters": RESEARCH_NODE_COUNTERS,
    "history": array(RESEARCH_NODE_HISTORY_ENTRY),
    "created_at": NULLABLE_DATE_TIME,
    "started_at": NULLABLE_DATE_TIME,
    "completed_at": NULLABLE_DATE_TIME,
    "last_error": STR,
    "paused_reason": STR,
}

MANIFEST_FIELDS = {
    "manifest_type": STR,
    "name": STR,
    "actor": STR,
    "consumer_path": STR,
    "target_options": array(JSON_VALUE),
    "document_ids": STRS,
    "counts_by_dtype": {"type": "object", "additionalProperties": INT},
    "record_count": INT,
    "hash_algorithm": STR,
    "content_hash": STR,
    "files": array(JSON_MAP),
    "schema_versions": STRS,
    "generated_at": NULLABLE_DATE_TIME,
}

BREACH_LEAK_TYPES = [
    "data-breach",
    "data-leak",
    "accidental-exposure",
    "ransomware-exfiltration",
    "insider-leak",
    "combo-list",
    "scraping-aggregation",
    "unknown",
]

BREACH_DATA_CATEGORIES = [
    "credentials",
    "email-addresses",
    "password-hash",
    "password-plaintext",
    "pii",
    "financial",
    "payment-card",
    "health",
    "source-code",
    "internal-documents",
    "database-dumps",
    "session-tokens",
    "api-keys",
    "private-keys",
    "geolocation",
    "authentication-cookies",
    "other",
]

BREACH_RECORD_COUNT_BASIS = [
    "operator-reported",
    "sample-extrapolated",
    "exact",
    "unknown",
]

BREACH_CORROBORATION_LEVELS = [
    "single-source-unverified",
    "multi-source",
    "officially-confirmed",
    "disputed",
    "unknown",
]

BREACH_DISTRIBUTION_OBSERVATION = obj(
    {
        "platform": STR,
        "url": STR,
        "actor_handle": STR,
        "first_seen": NULLABLE_DATE_TIME,
        "last_seen": NULLABLE_DATE_TIME,
    }
)

# SECURITY (docs/schema-0.10.1-design.md §6): breach documents never carry
# raw leaked material inline. Only counts, hashes, category labels, and
# artifact references are representable; leak_corpus_uri is reference-only.
# If a credential-material inline field is ever proposed, it must be rejected
# in review; the validator fails closed on these reserved names.
BREACH_FORBIDDEN_INLINE_FIELDS = frozenset(
    {
        "raw_records",
        "leaked_records",
        "credentials",
        "credential_dump",
        "password_dump",
        "plaintext_records",
        "raw_content",
        "dump_content",
        "leak_content",
        "records_inline",
    }
)

BREACH_FIELDS: dict[str, dict[str, Any]] = {
    "name": STR,
    "description": STR,
    "url": STR,
    "total": INT,
    "breached_at": NULLABLE_DATE_TIME,
    "discovered_at": NULLABLE_DATE_TIME,
    "data_classes": STRS,
    "organization_id": STR,
    "verified": BOOL,
    "leak_type": string(enum=list(BREACH_LEAK_TYPES)),
    "incident_date_start": NULLABLE_DATE_TIME,
    "incident_date_end": NULLABLE_DATE_TIME,
    "discovery_date": NULLABLE_DATE_TIME,
    "disclosed_date": NULLABLE_DATE_TIME,
    "published_date": NULLABLE_DATE_TIME,
    "data_categories": array(string(enum=list(BREACH_DATA_CATEGORIES))),
    "records_affected": INT,
    "record_count_basis": string(enum=list(BREACH_RECORD_COUNT_BASIS)),
    "sample_size": INT,
    "credential_count": INT,
    "unique_email_count": INT,
    "plaintext_password_count": INT,
    "hash_algorithms": STRS,
    "leaked_file_ids": STRS,
    "leak_corpus_uri": STR,
    "leak_corpus_sha256": STR,
    "distribution_observations": array(BREACH_DISTRIBUTION_OBSERVATION),
    "affected_org_ids": STRS,
    "affected_domain_ids": STRS,
    "affected_person_count": INT,
    "initial_access_vector": STR,
    "root_cause": STR,
    "cve_ids": STRS,
    "threat_actor_ids": STRS,
    "malware_families": STRS,
    "corroboration": string(enum=list(BREACH_CORROBORATION_LEVELS)),
    "hibp_breach_name": STR,
    "regulator_filing_refs": STRS,
}

CAPTCHA_CONTEXT_FIELDS: dict[str, dict[str, Any]] = {
    "challenge_status": STR,
    "captcha_detection_id": STR,
    "captcha_capability": STR,
    "browser_session_ref": STR,
    "network_context_ref": STR,
    "proxy_actor_uri": STR,
}

# Folded verbatim from the superseded 0.9.2 network-capture profile
# (starintel_doc/spec_092.py); see docs/schema-0.10.1-design.md §5.3.
HTTP_TRANSACTION_FIELDS: dict[str, dict[str, Any]] = {
    "transaction_id": STR,
    "request_id": STR,
    "connection_id": STR,
    "parent_transaction_id": STR,
    "method": STR,
    "url": STR,
    "scheme": STR,
    "host": STR,
    "port": INT,
    "path": STR,
    "query": STR,
    "http_version": STR,
    "request_headers": JSON_MAP,
    "request_body_size": INT,
    "request_body_hash": STR,
    "request_body_artifact_uri": STR,
    "response_status": INT,
    "response_reason": STR,
    "response_headers": JSON_MAP,
    "response_body_size": INT,
    "response_body_hash": STR,
    "response_body_artifact_uri": STR,
    "started_at": NULLABLE_DATE_TIME,
    "ended_at": NULLABLE_DATE_TIME,
    "duration_ms": NUM,
    "remote_ip": STR,
    "remote_port": INT,
    "tls_version": STR,
    "tls_cipher": STR,
    "tls_server_name": STR,
    "certificate_sha256": STR,
    "redirect_from_id": STR,
    "redirect_to_id": STR,
    "capture_actor_uri": STR,
    **CAPTCHA_CONTEXT_FIELDS,
    "redacted_headers": STRS,
    "body_capture_policy": STR,
    "request_truncated": BOOL,
    "response_truncated": BOOL,
}

WEB_CAPTURE_FIELDS: dict[str, dict[str, Any]] = {
    "capture_id": STR,
    "url": STR,
    "final_url": STR,
    "title": STR,
    "status_code": INT,
    "browser": STR,
    "browser_version": STR,
    "viewport_width": INT,
    "viewport_height": INT,
    "device_scale_factor": NUM,
    "screenshot_uri": STR,
    "screenshot_hash": STR,
    "screenshot_media_type": STR,
    "screenshot_size_bytes": INT,
    "dom_artifact_uri": STR,
    "dom_artifact_hash": STR,
    "dom_artifact_size_bytes": INT,
    "captured_at": NULLABLE_DATE_TIME,
    "http_transaction_ids": STRS,
    "capture_actor_uri": STR,
    **CAPTCHA_CONTEXT_FIELDS,
}

NETWORK_DEVICE_FIELDS: dict[str, dict[str, Any]] = {
    "device_class": string(enum=list(DEVICE_CLASS_VALUES)),
    "device_id": STR,
    "vendor": STR,
    "model": STR,
    "serial_number": STR,
    "hardware_class": string(enum=HARDWARE_CLASS_VALUES),
    "firmware_version": STR,
    "cpe": STR,
    "management_addr_ids": STRS,
    "site_id": STR,
    "parent_device_id": STR,
    "hosted_host_ids": STRS,
    "discovered_by_ids": STRS,
    "first_seen": NULLABLE_DATE_TIME,
    "last_seen": NULLABLE_DATE_TIME,
    "notes_ref": STR,
}

PCAP_CAPTURE_FIELDS: dict[str, dict[str, Any]] = {
    "capture_id": STR,
    "file_uri": STR,
    "file_sha256": STR,
    "format": string(enum=["pcap", "pcapng", "unknown"]),
    "file_size_bytes": INT,
    "packet_count": INT,
    "capture_start": NULLABLE_DATE_TIME,
    "capture_end": NULLABLE_DATE_TIME,
    "duration_seconds": NUM,
    "interfaces": array(obj({"name": STR, "iftype": INT, "mac": STR, "snaplen": INT})),
    "protocol_hierarchy": array(
        obj({"protocol": STR, "frames": INT, "bytes": INT, "pct_frames": NUM, "pct_bytes": NUM})
    ),
    "analysis_actor_uri": STR,
    "sensor_ref": STR,
    "capture_software": STR,
}

CONVERSATION_ENDPOINT = obj(
    {
        "host_id": STR,
        "mac": STR,
        "ipv4": STR,
        "ipv6": STR,
        "port": INT,
    }
)

NETWORK_CONVERSATION_FIELDS: dict[str, dict[str, Any]] = {
    "conversation_id": STR,
    "capture_id": STR,
    "layer": string(enum=["eth", "ip", "ipv6", "tcp", "udp"]),
    "a_endpoint": CONVERSATION_ENDPOINT,
    "b_endpoint": CONVERSATION_ENDPOINT,
    "protocols": STRS,
    "a_packets": INT,
    "b_packets": INT,
    "a_bytes": INT,
    "b_bytes": INT,
    "first_frame_num": INT,
    "last_frame_num": INT,
    "started_at": NULLABLE_DATE_TIME,
    "ended_at": NULLABLE_DATE_TIME,
    "duration_seconds": NUM,
}

WIRELESS_NETWORK_FIELDS: dict[str, dict[str, Any]] = {
    "bssid": STR,
    "security": string(
        enum=[
            "open",
            "wep",
            "wpa-psk",
            "wpa2-psk",
            "wpa2-enterprise",
            "wpa3-psk",
            "wpa3-enterprise",
            "wpa2wpa3-psk",
            "unknown",
        ]
    ),
    "ssid": STR,
    "cipher_suite": STR,
    "auth_mode": STR,
    "channel": INT,
    "frequency_mhz": INT,
    "band": string(enum=["2.4ghz", "5ghz", "6ghz", "unknown"]),
    "signal_dbm": INT,
    "latitude": NUM,
    "longitude": NUM,
    "location_accuracy_m": NUM,
    "observations": INT,
    "client_count": INT,
    "first_seen": NULLABLE_DATE_TIME,
    "last_seen": NULLABLE_DATE_TIME,
    "source_network_id": STR,
    "vendor": STR,
    "hosted_host_id": STR,
    "qos": INT,
}

WIRELESS_STATION_FIELDS: dict[str, dict[str, Any]] = {
    "mac": STR,
    "station_type": string(enum=["station", "ap", "bridge", "bridge-ap", "unknown"]),
    "vendor": STR,
    "probe_ssids": STRS,
    "last_bssid": STR,
    "signal_dbm": INT,
    "observations": INT,
    "first_seen": NULLABLE_DATE_TIME,
    "last_seen": NULLABLE_DATE_TIME,
    "source_device_id": STR,
    "packets": INT,
    "data_bytes": INT,
}

TYPE_FIELDS: dict[str, dict[str, Any]] = {
    "document": {},
    "entity": ENTITY_FIELDS,
    "person": PERSON_FIELDS,
    "org": ORG_FIELDS,
    "relation": RELATION_FIELDS,
    "target": TARGET_FIELDS,
    "investigation-target": TARGET_FIELDS,
    "domain": DOMAIN_FIELDS,
    "network": NETWORK_FIELDS,
    "host": HOST_FIELDS,
    "url": URL_FIELDS,
    "geo": LOCATION_FIELDS,
    "address": LOCATION_FIELDS,
    "location": LOCATION_FIELDS,
    "phone": {**CONTACT_FIELDS, "number": STR, "carrier": STR, "phone_type": STR, "country_code": STR, "extension": STR},
    "email": {**CONTACT_FIELDS, "user": STR, "domain": STR, "address": STR, "display_name": STR},
    "email-message": {
        **MESSAGE_FIELDS,
        "body": STR,
        "subject": STR,
        "to": STRS,
        "from": STR,
        "cc": STRS,
        "bcc": STRS,
        "headers": JSON_MAP,
        "attachments": STRS,
    },
    "user": {**ENTITY_FIELDS, "url": STR, "username": STR, "platform": STR, "bio": STR, "misc": array(JSON_MAP)},
    "message": MESSAGE_FIELDS,
    "social-media-post": POST_FIELDS,
    "breach": BREACH_FIELDS,
    "product": PRODUCT_FIELDS,
    "event": EVENT_FIELDS,
    "meeting": EVENT_FIELDS,
    "claim": CLAIM_FIELDS,
    "analysis": ANALYSIS_FIELDS,
    "concept": {"term": STR, "definition": STR, "domain": STR, "broader_ids": STRS, "narrower_ids": STRS, "related_ids": STRS, "examples": STRS, "criteria": STRS},
    "observation": {"observer_id": STR, "subject_id": STR, "observation_type": STR, "value": JSON_VALUE, "unit": STR, "method": STR, "instrument": STR, "observed_at": NULLABLE_DATE_TIME},
    "financial-observation": FINANCIAL_FIELDS,
    "contract": CONTRACT_FIELDS,
    "procurement": CONTRACT_FIELDS,
    "grant": {**CONTRACT_FIELDS, "grantor_id": STR, "recipient_ids": STRS, "program": STR, "assistance_listing": STR, "matching_required": BOOL},
    "lobbying-filing": LOBBYING_FIELDS,
    "campaign-finance": {**FINANCIAL_FIELDS, "committee_id": STR, "donor_id": STR, "recipient_id": STR, "filing_id": STR, "contribution_type": STR, "election_cycle": STR},
    "legal-case": LEGAL_FIELDS,
    "policy": {"policy_id": STR, "name": STR, "issuer_id": STR, "jurisdiction": STR, "policy_type": STR, "text": STR, "effective_at": NULLABLE_DATE_TIME, "expires_at": NULLABLE_DATE_TIME, "status": STR, "affected_ids": STRS},
    "education": {"person_id": STR, "institution_id": STR, "degree": STR, "field": STR, "start_at": NULLABLE_DATE_TIME, "end_at": NULLABLE_DATE_TIME, "graduated": BOOL, "honors": STRS},
    "employment": {"person_id": STR, "organization_id": STR, "title": STR, "department": STR, "start_at": NULLABLE_DATE_TIME, "end_at": NULLABLE_DATE_TIME, "current": BOOL, "employment_type": STR, "location_id": STR},
    "ownership": {"owner_id": STR, "asset_id": STR, "ownership_type": STR, "percentage": NUM, "units": NUM, "start_at": NULLABLE_DATE_TIME, "end_at": NULLABLE_DATE_TIME, "beneficial": BOOL, "direct": BOOL},
    "asset": {**ENTITY_FIELDS, "asset_type": STR, "owner_ids": STRS, "operator_ids": STRS, "serial_number": STR, "registration": STR, "value": NUM, "currency": STR, "location_id": STR, "status": STR},
    "media": {"title": STR, "media_type": STR, "uri": STR, "creator_ids": STRS, "publisher_id": STR, "published_at": NULLABLE_DATE_TIME, "duration_seconds": NUM, "transcript": STR, "content_hash": STR, "license": STR},
    "file": {"name": STR, "path": STR, "uri": STR, "media_type": STR, "size_bytes": INT, "content_hash": STR, "hash_algorithm": STR, "created_at": NULLABLE_DATE_TIME, "modified_at": NULLABLE_DATE_TIME, "owner_id": STR},
    "source": SOURCE["properties"],
    "evidence-record": EVIDENCE["properties"],
    "research-pass": RESEARCH_PASS_FIELDS,
    "research-node": RESEARCH_NODE_FIELDS,
    "actor-manifest": MANIFEST_FIELDS,
    "dataset-manifest": MANIFEST_FIELDS,
    "alert": {"alert_type": STR, "subject_ids": STRS, "condition": STR, "threshold": NUM, "triggered_at": NULLABLE_DATE_TIME, "severity": NUM, "status": STR, "acknowledged_by": STRS},
    "task": {"task_type": STR, "subject_ids": STRS, "assignee_ids": STRS, "status": STR, "priority": NUM, "due_at": NULLABLE_DATE_TIME, "completed_at": NULLABLE_DATE_TIME, "instructions": STR, "result_ids": STRS},
    "http-transaction": HTTP_TRANSACTION_FIELDS,
    "web-capture": WEB_CAPTURE_FIELDS,
    "network-device": NETWORK_DEVICE_FIELDS,
    "pcap-capture": PCAP_CAPTURE_FIELDS,
    "network-conversation": NETWORK_CONVERSATION_FIELDS,
    "wireless-network": WIRELESS_NETWORK_FIELDS,
    "wireless-station": WIRELESS_STATION_FIELDS,
}

# --- 0.10.1 unify: expansion vocabulary absorbed into the wire spec ---------
# The retired 0.9 expansion registry's per-dtype profile vocabulary is now
# real wire vocabulary (docs/schema-0.10.1-design.md §3-§4). Wire fields
# above always win over absorbed names; the four common data fields below
# have the lowest precedence and apply to every dtype.
ABSORBED_COMMON_DATA_FIELDS: dict[str, Any] = {
    "description": STR,
    "status": STR,
    "valid_from": NULLABLE_DATE_TIME,
    "valid_to": NULLABLE_DATE_TIME,
}

EXPANSION_ABSORBED_FIELDS: dict[str, dict[str, Any]] = {
    "actor-manifest": {
        "actor_id": STR,
        "actor_type": STR,
        "implementation": STR,
        "entrypoint": STR,
        "input_dtypes": STRS,
        "output_dtypes": STRS,
        "dependencies": STRS,
        "routing_keys": STRS,
        "configuration_schema": JSON_VALUE,
        "capabilities": STRS,
        "healthcheck": JSON_VALUE,
        "schema_revision": STR,
    },
    "address": {
        "formatted": STR,
        "address_type": STR,
        "building": STR,
        "unit": STR,
        "district": STR,
        "administrative_areas": STRS,
        "geometry": JSON_VALUE,
        "occupant_ids": STRS,
    },
    "alert": {
        "rule_id": STR,
        "trigger_event_id": STR,
        "related_alert_ids": STRS,
        "first_triggered_at": NULLABLE_DATE_TIME,
        "last_triggered_at": NULLABLE_DATE_TIME,
        "occurrence_count": INT,
        "acknowledgement_actions": array(JSON_MAP),
        "suppressed_until": STR,
        "resolved_at": NULLABLE_DATE_TIME,
        "resolution": STR,
    },
    "analysis": {
        "hypotheses": STRS,
        "method_ids": STRS,
        "claim_ids": STRS,
        "logic": STR,
        "reasoning_artifact_ids": STRS,
        "uncertainty_sources": STRS,
        "dependency_ids": STRS,
        "review_ids": STRS,
        "output_ids": STRS,
    },
    "asset": {
        "asset_class": STR,
        "custodian_ids": STRS,
        "beneficial_owner_ids": STRS,
        "identifier_records": array(IDENTIFIER),
        "valuation_records": array(MONEY),
        "acquired_at": NULLABLE_DATE_TIME,
        "disposed_at": NULLABLE_DATE_TIME,
        "acquisition_event_id": STR,
        "disposal_event_id": STR,
        "component_ids": STRS,
    },
    "breach": {
        "affected_org_ids": STRS,
        "affected_product_ids": STRS,
        "record_count_estimate": INT,
        "record_count_basis": STR,
        "data_class_records": array(JSON_MAP),
        "disclosure_source_ids": STRS,
        "notification_ids": STRS,
        "severity_score": SCORE,
        "incident_ids": STRS,
    },
    "campaign-finance": {
        "transaction_id": STR,
        "committee_ids": STRS,
        "donor_refs": STRS,
        "recipient_refs": STRS,
        "amount_record": MONEY,
        "transaction_date": STR,
        "memoed": BOOL,
        "memo_text": STR,
        "refund_of_id": STR,
        "aggregate_amount": MONEY,
        "employer": STR,
        "occupation": STR,
        "source_system_ids": array(IDENTIFIER),
    },
    "claim": {
        "proposition": STR,
        "subject_refs": STRS,
        "object_refs": STRS,
        "supporting_source_ids": STRS,
        "review_ids": STRS,
        "truth_status": STR,
        "verification_method": STRS,
        "derived_from_claim_ids": STRS,
        "scope": STR,
    },
    "concept": {
        "concept_id": STR,
        "vocabulary": STR,
        "namespace": STR,
        "version": STR,
        "preferred_label": STR,
        "synonyms": STRS,
        "definition_source_ids": STRS,
        "mapping_ids": STRS,
    },
    "contract": {
        "parent_award_id": STR,
        "prime_award_id": STR,
        "party_roles": array(JSON_MAP),
        "funding_records": array(MONEY),
        "line_items": array(JSON_MAP),
        "clause_ids": STRS,
        "deliverable_ids": STRS,
        "performance_location_ids": STRS,
        "source_system_ids": array(IDENTIFIER),
    },
    "dataset-manifest": {
        "dataset_id": STR,
        "dataset_version": STR,
        "profile": STR,
        "profile_version": STR,
        "schema_revision": STR,
        "document_versions": STRS,
        "source_dataset_ids": STRS,
        "sync_cursor": STR,
        "sync_status": STR,
        "validated_at": NULLABLE_DATE_TIME,
    },
    "document": {
        "document_kind": STR,
        "body": STR,
        "format": STR,
        "author_ids": STRS,
        "publisher_id": STR,
        "section_ids": STRS,
        "published_at": NULLABLE_DATE_TIME,
        "revision_label": STR,
    },
    "domain": {
        "unicode_domain": STR,
        "punycode_domain": STR,
        "tld": STR,
        "registrar_id": STR,
        "registrant_ids": STRS,
        "certificate_ids": STRS,
        "url_ids": STRS,
        "mail_exchange_hosts": STRS,
        "zone_hash": STR,
    },
    "education": {
        "education_type": STR,
        "credential_id": STR,
        "program_id": STR,
        "attendance_status": STR,
        "awarded_at": NULLABLE_DATE_TIME,
        "thesis_title": STR,
        "advisor_ids": STRS,
    },
    "email": {
        "normalized_address": STR,
        "local_part": STR,
        "domain_id": STR,
        "owner_ids": STRS,
        "provider_id": STR,
        "usage_types": STRS,
        "account_ids": STRS,
        "deliverability_status": STR,
    },
    "email-message": {
        "sender_refs": STRS,
        "recipient_refs": STRS,
        "reply_to_refs": STRS,
        "message_id_header": STR,
        "in_reply_to_ids": STRS,
        "reference_message_ids": STRS,
        "body_file_ids": STRS,
        "attachment_ids": STRS,
        "authentication_results": JSON_VALUE,
        "transport_hops": array(JSON_MAP),
    },
    "employment": {
        "role_ids": STRS,
        "reports_to_ids": STRS,
        "appointment_type": STR,
        "appointed_by_ids": STRS,
        "compensation_records": array(MONEY),
        "responsibilities": STRS,
        "termination_reason": STR,
    },
    "entity": {
        "entity_class": STR,
        "canonical_name": STR,
        "same_as_ids": STRS,
        "duplicate_candidate_ids": STRS,
        "identity_confidence": SCORE,
        "identity_keys": array(IDENTIFIER),
    },
    "event": {
        "event_type_id": STR,
        "parent_event_id": STR,
        "child_event_ids": STRS,
        "participant_roles": array(JSON_MAP),
        "action_records": array(JSON_MAP),
        "source_event_ids": STRS,
        "recurrence_rule": STR,
        "result_ids": STRS,
        "claim_ids": STRS,
    },
    "evidence-record": {
        "subject_ids": STRS,
        "claim_ids": STRS,
        "exact_content": STR,
        "normalized_content": STR,
        "extraction_method": STR,
        "capture_action_id": STR,
        "custody_actions": array(JSON_MAP),
        "hashes": JSON_MAP,
        "admissibility_status": STR,
    },
    "file": {
        "storage_id": STR,
        "original_name": STR,
        "extension": STR,
        "magic_type": STR,
        "hashes": JSON_MAP,
        "parent_file_id": STR,
        "container_file_id": STR,
        "derived_file_ids": STRS,
        "capture_action_id": STR,
        "extracted_metadata": JSON_VALUE,
        "quarantined": BOOL,
    },
    "financial-observation": {
        "transaction_id": STR,
        "payer_ids": STRS,
        "payee_ids": STRS,
        "account_ids": STRS,
        "amount_record": MONEY,
        "amount_basis": STR,
        "reporting_standard": STR,
        "filing_ids": STRS,
        "source_transaction_ids": STRS,
        "memoed": BOOL,
        "refunded": BOOL,
    },
    "geo": {
        "geometry_type": STR,
        "coordinates": array(NUM),
        "geometry": JSON_VALUE,
        "feature_type": STR,
        "accuracy_meters": NUM,
        "source_coordinate_system": STR,
        "address_ids": STRS,
        "contains_ids": STRS,
        "contained_by_ids": STRS,
    },
    "grant": {
        "award_number": STR,
        "prime_recipient_id": STR,
        "subrecipient_ids": STRS,
        "program_id": STR,
        "funding_records": array(MONEY),
        "assistance_listing_ids": STRS,
        "matching_amount": MONEY,
        "performance_location_ids": STRS,
        "objective_ids": STRS,
        "report_ids": STRS,
    },
    "host": {
        "host_type": STR,
        "interface_records": array(JSON_MAP),
        "service_records": array(JSON_MAP),
        "certificate_records": array(JSON_MAP),
        "software_ids": STRS,
        "cloud_account_ids": STRS,
        "virtualization_type": STR,
        "parent_host_id": STR,
        "observed_by_ids": STRS,
    },
    "investigation-target": {
        "target_ids": STRS,
        "root_target_id": STR,
        "parent_target_id": STR,
        "depends_on_target_ids": STRS,
        "completion_criteria": STRS,
        "stop_conditions": STRS,
        "deliverables": STRS,
        "result_ids": STRS,
        "attempt_count": INT,
        "last_run_at": NULLABLE_DATE_TIME,
    },
    "legal-case": {
        "court_id": STR,
        "docket_id": STR,
        "party_roles": array(JSON_MAP),
        "related_case_ids": STRS,
        "motion_ids": STRS,
        "order_ids": STRS,
        "opinion_ids": STRS,
        "appeal_case_ids": STRS,
        "disposition": STR,
        "precedential_status": STR,
    },
    "lobbying-filing": {
        "filing_system": STR,
        "registrant_refs": STRS,
        "client_refs": STRS,
        "lobbyist_refs": STRS,
        "covered_official_ids": STRS,
        "issue_codes": STRS,
        "amount_records": array(MONEY),
        "foreign_entity_ids": STRS,
        "prior_filing_id": STR,
        "amends_filing_id": STR,
        "source_filing_url": STR,
    },
    "location": {
        "geometry_type": STR,
        "coordinates": array(NUM),
        "geometry": JSON_VALUE,
        "feature_type": STR,
        "accuracy_meters": NUM,
        "address_ids": STRS,
        "contains_ids": STRS,
        "contained_by_ids": STRS,
        "jurisdiction_ids": STRS,
    },
    "media": {
        "source_file_id": STR,
        "derivative_file_ids": STRS,
        "creator_refs": STRS,
        "capture_action_id": STR,
        "width": INT,
        "height": INT,
        "codec": STR,
        "language": STR,
        "ocr_text": STR,
        "transcript_file_id": STR,
        "hashes": JSON_MAP,
    },
    "meeting": {
        "meeting_type": STR,
        "chair_ids": STRS,
        "attendee_roles": array(JSON_MAP),
        "agenda_item_ids": STRS,
        "minute_file_ids": STRS,
        "decision_ids": STRS,
        "action_item_ids": STRS,
        "parent_meeting_id": STR,
        "recurrence_rule": STR,
    },
    "message": {
        "author_refs": STRS,
        "recipient_refs": STRS,
        "conversation_id": STR,
        "parent_message_id": STR,
        "quoted_message_id": STR,
        "attachment_ids": STRS,
        "capture_ids": STRS,
        "content_hash": STR,
    },
    "network": {
        "network_type": STR,
        "prefixes": STRS,
        "allocation_id": STR,
        "registrant_id": STR,
        "contact_ids": STRS,
        "routing_policy": STRS,
        "bgp_observation_ids": STRS,
        "announced_by_asns": array(INT),
        "rpki_status": STR,
    },
    "observation": {
        "subject_refs": STRS,
        "observed_property": STR,
        "raw_value": JSON_VALUE,
        "action_id": STR,
        "observer_refs": STRS,
        "uncertainty": NUM,
    },
    "org": {
        "legal_form": STR,
        "incorporated_at": NULLABLE_DATE_TIME,
        "incorporation_location_id": STR,
        "registration_ids": array(IDENTIFIER),
        "headquarters_id": STR,
        "office_location_ids": STRS,
        "leadership_role_ids": STRS,
        "governance_document_ids": STRS,
        "filing_ids": STRS,
        "contract_ids": STRS,
        "grant_ids": STRS,
        "lobbying_filing_ids": STRS,
        "campaign_finance_ids": STRS,
        "financial_observation_ids": STRS,
        "same_as_ids": STRS,
    },
    "ownership": {
        "owner_refs": STRS,
        "owned_refs": STRS,
        "ownership_instrument": STR,
        "percentage_basis": STR,
        "voting_percentage": NUM,
        "economic_percentage": NUM,
        "value_record": MONEY,
        "acquisition_event_id": STR,
        "disposal_event_id": STR,
    },
    "person": {
        "canonical_name": STR,
        "name_parts": JSON_VALUE,
        "birth_date_precision": STR,
        "birth_location_id": STR,
        "residence_ids": STRS,
        "employment_ids": STRS,
        "membership_ids": STRS,
        "public_office_ids": STRS,
        "ownership_ids": STRS,
        "campaign_finance_ids": STRS,
        "legal_case_ids": STRS,
        "biography_source_ids": STRS,
        "same_as_ids": STRS,
    },
    "phone": {
        "normalized_number": STR,
        "e164": STR,
        "subscriber_id": STR,
        "provider_id": STR,
        "usage_types": STRS,
        "porting_history": STR,
        "account_ids": STRS,
    },
    "policy": {
        "policy_version": STR,
        "parent_policy_id": STR,
        "authority_ids": STRS,
        "implementation_ids": STRS,
        "text_file_ids": STRS,
        "section_ids": STRS,
        "adopted_at": NULLABLE_DATE_TIME,
        "repealed_at": NULLABLE_DATE_TIME,
        "superseded_by_id": STR,
        "compliance_requirement_ids": STRS,
    },
    "procurement": {
        "procurement_stage": STR,
        "notice_id": STR,
        "parent_award_id": STR,
        "party_roles": array(JSON_MAP),
        "funding_records": array(MONEY),
        "line_items": array(JSON_MAP),
        "competition_exceptions": STRS,
        "evaluation_criteria": STRS,
        "source_system_ids": array(IDENTIFIER),
    },
    "product": {
        "supplier_ids": STRS,
        "version_ids": STRS,
        "component_ids": STRS,
        "dependency_ids": STRS,
        "deployment_ids": STRS,
        "sbom_file_ids": STRS,
        "support_end_at": NULLABLE_DATE_TIME,
        "pricing_records": array(MONEY),
        "security_advisory_ids": STRS,
    },
    "relation": {
        "statement_id": STR,
        "predicate_id": STR,
        "predicate_namespace": STR,
        "subject_role": STR,
        "object_role": STR,
        "subject_dtype": STR,
        "object_dtype": STR,
        "asserted_by_ids": STRS,
        "supporting_evidence_ids": STRS,
        "contradicting_evidence_ids": STRS,
        "negated": BOOL,
        "symmetric": BOOL,
        "transitive": BOOL,
        "qualifier_records": array(JSON_MAP),
    },
    "research-pass": {
        "parent_pass_id": STR,
        "child_pass_ids": STRS,
        "target_ids": STRS,
        "action_records": array(JSON_MAP),
        "claim_ids": STRS,
        "output_ids": STRS,
        "metrics": JSON_VALUE,
        "termination_reason": STR,
        "schema_revision": STR,
    },
    "social-media-post": {
        "author_refs": STRS,
        "conversation_id": STR,
        "parent_post_id": STR,
        "attachment_ids": STRS,
        "capture_ids": STRS,
        "engagement_observation_ids": STRS,
        "content_hash": STR,
    },
    "source": {
        "source_type_id": STR,
        "publisher_id": STR,
        "author_ids": STRS,
        "capture_action_id": STR,
        "original_file_ids": STRS,
        "archive_ids": STRS,
        "terms_of_use": STR,
        "access_restrictions": STRS,
        "supersedes_source_ids": STRS,
    },
    "target": {
        "target_ids": STRS,
        "root_target_id": STR,
        "parent_target_id": STR,
        "depends_on_target_ids": STRS,
        "completion_criteria": STRS,
        "stop_conditions": STRS,
        "deliverables": STRS,
        "result_ids": STRS,
        "attempt_count": INT,
        "last_run_at": NULLABLE_DATE_TIME,
    },
    "task": {
        "parent_task_id": STR,
        "dependency_task_ids": STRS,
        "actor_ids": STRS,
        "skill_ids": STRS,
        "tool_ids": STRS,
        "input_ids": STRS,
        "attempt_ids": STRS,
        "schedule": STR,
        "started_at": NULLABLE_DATE_TIME,
        "result_summary": STR,
        "error_ids": STRS,
    },
    "url": {
        "canonical_url": STR,
        "final_url": STR,
        "parent_url_id": STR,
        "discovered_from_ids": STRS,
        "http_exchanges": array(JSON_MAP),
        "archive_ids": STRS,
        "screenshot_ids": STRS,
        "content_file_ids": STRS,
        "crawl_depth": INT,
        "robots_allowed": BOOL,
    },
    "user": {
        "account_id": STR,
        "platform_id": STR,
        "profile_url": STR,
        "created_at": NULLABLE_DATE_TIME,
        "last_active_at": NULLABLE_DATE_TIME,
        "owner_ids": STRS,
        "follower_count": INT,
        "following_count": INT,
        "post_count": INT,
        "account_status": STR,
        "verified_type": STR,
    },
}

for _dtype in TYPE_FIELDS:
    TYPE_FIELDS[_dtype] = {**ABSORBED_COMMON_DATA_FIELDS, **TYPE_FIELDS[_dtype]}
for _dtype, _absorbed in EXPANSION_ABSORBED_FIELDS.items():
    if _dtype not in TYPE_FIELDS:
        raise KeyError(f"expansion absorption references unknown dtype {_dtype!r}")
    TYPE_FIELDS[_dtype] = {**ABSORBED_COMMON_DATA_FIELDS, **_absorbed, **TYPE_FIELDS[_dtype]}
del _dtype, _absorbed


REQUIRED_DATA_FIELDS: dict[str, tuple[str, ...]] = {
    "research-node": ("objective", "status"),
    "relation": ("subject", "predicate", "object"),
    "target": ("target",),
    "investigation-target": ("target",),
    "phone": ("number",),
    "email": ("address",),
    "domain": ("domain",),
    "url": ("url",),
    "claim": ("claim",),
    "breach": ("name",),
    "http-transaction": ("transaction_id", "method", "url", "response_status"),
    "web-capture": ("capture_id", "url", "screenshot_uri", "screenshot_hash"),
    "network-device": ("device_class",),
    "pcap-capture": ("capture_id", "file_uri", "file_sha256"),
    "network-conversation": ("conversation_id", "capture_id", "layer"),
    "wireless-network": ("bssid", "security"),
    "wireless-station": ("mac",),
}

DTYPE_ALIASES = {
    "organization": "org",
    "organisation": "org",
    "investigation_target": "investigation-target",
    "social_media_post": "social-media-post",
    "email_message": "email-message",
    "financial_observation": "financial-observation",
    "research_pass": "research-pass",
    "research_node": "research-node",
    "dataset_manifest": "dataset-manifest",
    "actor_manifest": "actor-manifest",
    "legal_case": "legal-case",
    "lobbying_filing": "lobbying-filing",
    "campaign_finance": "campaign-finance",
    "http_transaction": "http-transaction",
    "web_capture": "web-capture",
    "network_device": "network-device",
}

COMMON_PROPERTIES: dict[str, Any] = {
    "_id": string(pattern=r"^[^/\\\x00]+$"),
    "_rev": STR,
    "dataset": STR,
    "dtype": string(enum=sorted(TYPE_FIELDS)),
    # Migration window (docs/schema-0.10.1-design.md §7): validators accept
    # the legacy 0.9.0 envelope and the 0.10.1 envelope; emitters write
    # SCHEMA_VERSION.
    "schema_version": {"enum": list(SCHEMA_VERSIONS_ENUM)},
    "version": integer(minimum=1),
    "date_added": DATE_TIME,
    "date_updated": DATE_TIME,
    "title": STR,
    "summary": STR,
    "description": STR,
    "status": STR,
    "language": STR,
    "tags": STRS,
    "labels": STRS,
    "aliases": STRS,
    "keywords": STRS,
    "identifiers": array(IDENTIFIER),
    "sources": array(SOURCE),
    "evidence": array(EVIDENCE),
    "temporal": TEMPORAL,
    "provenance": PROVENANCE,
    "assessment": ASSESSMENT,
    "verification": VERIFICATION,
    "handling": HANDLING,
    "lineage": LINEAGE,
    "quality": QUALITY,
    "workflow": WORKFLOW,
    "geospatial": GEOSPATIAL,
    "attachments": array(ATTACHMENT),
    "related_ids": STRS,
    "notes": STRS,
    "data": {"type": "object"},
    "extensions": {"type": "object", "additionalProperties": True},
}

REQUIRED_COMMON = (
    "_id",
    "dataset",
    "dtype",
    "schema_version",
    "version",
    "date_added",
    "date_updated",
    "sources",
    "evidence",
    "data",
)


def data_schema(dtype: str) -> dict[str, Any]:
    canonical = DTYPE_ALIASES.get(dtype, dtype)
    if canonical not in TYPE_FIELDS:
        raise KeyError(f"unknown dtype: {dtype}")
    return obj(
        deepcopy(TYPE_FIELDS[canonical]),
        required=REQUIRED_DATA_FIELDS.get(canonical, ()),
        additional=False,
    )


def document_schema(dtype: str | None = None) -> dict[str, Any]:
    properties = deepcopy(COMMON_PROPERTIES)
    if dtype is None:
        variants = []
        for name in sorted(TYPE_FIELDS):
            variants.append(
                {
                    "if": {"properties": {"dtype": {"const": name}}},
                    "then": {"properties": {"data": data_schema(name)}},
                }
            )
        return {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": SCHEMA_ID,
            "title": f"StarIntel Document v{SCHEMA_VERSION}",
            "type": "object",
            "properties": properties,
            "required": list(REQUIRED_COMMON),
            "additionalProperties": False,
            "allOf": variants,
        }
    canonical = DTYPE_ALIASES.get(dtype, dtype)
    properties["dtype"] = {"const": canonical}
    properties["data"] = data_schema(canonical)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{SCHEMA_ID}#{canonical}",
        "title": f"StarIntel {canonical} document v{SCHEMA_VERSION}",
        "type": "object",
        "properties": properties,
        "required": list(REQUIRED_COMMON),
        "additionalProperties": False,
    }
