"""Star-Lang export of the StarIntel document vocabulary.

Generates the canonical ``.star`` spec-library projection of
``starintel_doc/spec.py`` so every Star-Lang consumer (Common Lisp runtime,
portable manifests, generated bindings) can consume the same vocabulary that
the JSON Schema serves to schema-language consumers.

The generated library is a *semantic* authority:

- declaration and wire field names are ASCII lower camelCase per Star-Lang;
- the JSON Schema (``schemas/starintel-doc-<version>.schema.json``) remains
  the wire authority for the envelope JSON (snake_case ``data`` payloads);
- nullable wire fields (``["string", "null"]``) export as their base type with
  ``:optional`` carrying the nullability.

Output is deterministic: dtypes, fields, and scalars are emitted in sorted
order and the bytes depend only on the ``starintel_doc.spec`` tables.
"""

from __future__ import annotations

import hashlib
import re
from typing import Any

from starintel_doc.spec import (
    DTYPE_ALIASES,
    REQUIRED_DATA_FIELDS,
    SCHEMA_VERSION,
    TYPE_FIELDS,
    document_schema,
)

LIBRARY_ID = "org.starintel/core@1"
BASE_DOCUMENT = "starintel-document"
ENVELOPE_FIELDS = (
    "_id",
    "_rev",
    "dataset",
    "dtype",
    "schema_version",
    "version",
    "date_added",
    "date_updated",
    "sources",
    "evidence",
    "aliases",
    "assessment",
    "attachments",
    "description",
    "extensions",
    "geospatial",
    "handling",
    "identifiers",
    "keywords",
    "labels",
    "language",
    "lineage",
    "notes",
    "provenance",
    "quality",
    "related_ids",
    "schema_org",
    "status",
    "summary",
    "tags",
    "temporal",
    "title",
    "verification",
    "workflow",
)
ENVELOPE_REQUIRED = ("_id", "dataset", "dtype", "schema_version", "version",
                     "date_added", "date_updated", "sources", "evidence")


def camel(name: str) -> str:
    parts = [p for p in name.split("_") if p]
    if name.startswith("_"):
        name = name.lstrip("_")
        parts = [p for p in name.split("_") if p] or ["id"]
    if not parts:
        raise ValueError(f"cannot camelCase {name!r}")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


class _Exporter:
    def __init__(self) -> None:
        self.enums: dict[tuple[str, ...], str] = {}
        self.enum_order: list[tuple[str, str, tuple[str, ...]]] = []

    def enum_name(self, dtype: str, field: str, values: tuple[str, ...]) -> str:
        existing = self.enums.get(values)
        if existing is not None:
            return existing
        name = f"{dtype}-{field}-kind".replace("_", "-")
        self.enums[values] = name
        self.enum_order.append((name, dtype, values))
        return name

    def star_type(self, kind: dict[str, Any], dtype: str, field: str) -> str:
        types = kind.get("type")
        if isinstance(types, list):
            types = [t for t in types if t != "null"] or ["string"]
        if kind.get("enum"):
            return self.enum_name(dtype, field, tuple(kind["enum"]))
        if types == ["array"] or (not types and kind.get("items") is not None):
            items = kind.get("items", {})
            if not items:
                return "(list any)"
            return f"(list {self.star_type(items, dtype, field)})"
        if types == ["string"]:
            return "string"
        if types == ["integer"]:
            return "integer"
        if types == ["number"]:
            return "decimal"
        if types == ["boolean"]:
            return "boolean"
        if types == ["object"] or not types:
            return "map"
        return "any"


def _enum_value_identifier(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9-]+", "-", value).strip("-")
    if not cleaned:
        cleaned = "unknown"
    if cleaned[0].isdigit():
        cleaned = "n-" + cleaned
    return cleaned


def render_library() -> str:
    exporter = _Exporter()
    lines: list[str] = [
        f"(spec-library \"{LIBRARY_ID}\"",
        f"  (:version \"{SCHEMA_VERSION}\")",
        "",
        "  ;; Generated by scripts/star-lang-export.py from the StarIntel",
        f"  ;; {SCHEMA_VERSION} vocabulary. Do not edit by hand; regenerate.",
        "  ;; The JSON Schema stays the wire authority for envelope JSON; this",
        "  ;; library is the semantic authority for Star-Lang consumers.",
        "",
    ]

    dtype_names = sorted(TYPE_FIELDS)
    reference_schema = document_schema(dtype_names[0])
    envelope_doc = [f"  (document {BASE_DOCUMENT}",
                    "    (:persistence persistent)"]
    for field in ENVELOPE_FIELDS:
        prop = reference_schema["properties"].get(field)
        if prop is None:
            continue
        marker = ":required" if field in ENVELOPE_REQUIRED else ":optional"
        ftype = exporter.star_type(prop, "document", field)
        envelope_doc.append(f"    ({camel(field)} {ftype} {marker})")
    envelope_doc.append(")")

    documents: list[str] = []
    for dtype in dtype_names:
        canonical = DTYPE_ALIASES.get(dtype, dtype)
        required = set(REQUIRED_DATA_FIELDS.get(canonical, ()))
        schema = document_schema(canonical)
        data_props = schema["properties"]["data"]["properties"]
        doc_lines = [f"  (document {canonical}",
                     f"    (:extends {BASE_DOCUMENT}"
                     " :persistence persistent)"]
        for field in sorted(data_props):
            ftype = exporter.star_type(data_props[field], canonical, field)
            marker = ":required" if field in required else ":optional"
            doc_lines.append(f"    ({camel(field)} {ftype} {marker})")
        doc_lines.append(")")
        documents.append("\n".join(doc_lines))

    for name, _dtype, values in sorted(exporter.enum_order):
        body = " ".join(_enum_value_identifier(v) for v in values)
        lines.append(f"  (enum {name}")
        lines.append(f"    ({body}))")
        lines.append("")

    lines.extend(envelope_doc)
    lines.append("")
    lines.extend("\n\n".join(documents).splitlines())
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def library_digest(text: str | None = None) -> str:
    if text is None:
        text = render_library()
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_library(path) -> str:
    from pathlib import Path

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render_library()
    target.write_text(text, encoding="utf-8", newline="\n")
    return library_digest(text)
