import std/[algorithm, json, os, strformat, strutils]

import starintel_doc/v090
import starintel_transport


const DefaultReport = "unverifed"


type MissingSource = object
  path: string
  line: int
  id: string
  dataset: string
  dtype: string
  title: string


type AuditState = object
  documents: int
  malformedSources: int
  missing: seq[MissingSource]
  errors: seq[string]


proc text(node: JsonNode; key: string; fallback = ""): string =
  if node.kind == JObject and node.hasKey(key) and node[key].kind == JString:
    return node[key].getStr()
  fallback


proc oneLine(value: string): string =
  value.replace("\t", " ").replace("\r", " ").replace("\n", " ").strip()


proc location(path: string; line: int): string =
  path & ":" & $line


proc sourceShapeError(source: JsonNode): string =
  case source.kind
  of JString:
    if source.getStr().strip().len == 0:
      return "empty source string"
  of JObject:
    if source.len == 0:
      return "empty source object"
    let hasRef =
      (source.hasKey("source_id") and source["source_id"].kind == JString and source["source_id"].getStr().strip().len > 0) or
      (source.hasKey("uri") and source["uri"].kind == JString and source["uri"].getStr().strip().len > 0) or
      (source.hasKey("url") and source["url"].kind == JString and source["url"].getStr().strip().len > 0)
    if not hasRef:
      return "source object has no source_id, uri, or url"
  else:
    return "source entry must be a string or object"
  ""


proc auditDocument(state: var AuditState; schema, document: JsonNode; path: string; line: int) =
  inc state.documents

  let checked = validateDocument(document, schema)
  if not checked.ok:
    state.errors.add(location(path, line) & ": " & checked.category & ": " & checked.message)
    return

  if not document.hasKey("sources"):
    state.errors.add(location(path, line) & ": missing sources field")
    return
  if document["sources"].kind != JArray:
    state.errors.add(location(path, line) & ": sources must be an array")
    return

  let sources = document["sources"]
  if sources.len == 0:
    state.missing.add(MissingSource(
      path: path,
      line: line,
      id: text(document, "_id", "<missing-id>"),
      dataset: text(document, "dataset"),
      dtype: text(document, "dtype"),
      title: text(document, "title")
    ))
    return

  for index in 0 ..< sources.len:
    let reason = sourceShapeError(sources[index])
    if reason.len > 0:
      inc state.malformedSources
      state.errors.add(location(path, line) & ": sources[" & $index & "]: " & reason)


proc auditRawLine(state: var AuditState; schema: JsonNode; raw, path: string; line: int) =
  if raw.strip().len == 0:
    return
  try:
    let document = parseJson(raw)
    if document.kind != JObject:
      state.errors.add(location(path, line) & ": expected JSON object")
      return
    auditDocument(state, schema, document, path, line)
  except JsonParsingError as exc:
    state.errors.add(location(path, line) & ": invalid JSON: " & exc.msg)


proc auditFile(state: var AuditState; schema: JsonNode; path: string; transport: bool) =
  try:
    if transport:
      forEachTransportLine(path, proc(raw: string; line: int) =
        auditRawLine(state, schema, raw, path, line)
      )
    else:
      var input = open(path, fmRead)
      defer: input.close()
      var raw: string
      var line = 0
      while input.readLine(raw):
        inc line
        auditRawLine(state, schema, raw, path, line)
  except CatchableError as exc:
    state.errors.add(path & ": read/decode failed: " & exc.msg)


proc writeMissingReport(root, reportPath: string; missing: seq[MissingSource]) =
  var rows = missing
  rows.sort(proc(a, b: MissingSource): int =
    result = cmp(a.path, b.path)
    if result == 0:
      result = cmp(a.line, b.line)
    if result == 0:
      result = cmp(a.id, b.id)
  )

  var output = newStringOfCap(max(1024, rows.len * 128))
  output.add("# StarIntel documents lacking sources\n")
  output.add("# Generated by scripts/starintel_validate.nim\n")
  output.add("# path\tline\t_id\tdtype\tdataset\ttitle\n")
  for item in rows:
    output.add(oneLine(relativePath(item.path, root)))
    output.add('\t')
    output.add($item.line)
    output.add('\t')
    output.add(oneLine(item.id))
    output.add('\t')
    output.add(oneLine(item.dtype))
    output.add('\t')
    output.add(oneLine(item.dataset))
    output.add('\t')
    output.add(oneLine(item.title))
    output.add('\n')
  writeFile(reportPath, output)


proc usage() =
  echo "usage: starintel_validate [--root PATH] [--report PATH] [--require-sources]"


proc main(): int =
  var root = "."
  var report = ""
  var requireSources = false
  var index = 1
  while index <= paramCount():
    let arg = paramStr(index)
    case arg
    of "--root":
      inc index
      if index > paramCount():
        usage()
        return 2
      root = paramStr(index)
    of "--report":
      inc index
      if index > paramCount():
        usage()
        return 2
      report = paramStr(index)
    of "--require-sources":
      requireSources = true
    of "-h", "--help":
      usage()
      return 0
    else:
      stderr.writeLine("unknown argument: " & arg)
      usage()
      return 2
    inc index

  root = absolutePath(root)
  if report.len == 0:
    report = root / DefaultReport
  elif not report.isAbsolute:
    report = root / report

  putEnv("STARINTEL_SCHEMA", root / "schemas" / "starintel-doc-v0.9.0.schema.json")
  let schema = loadSchema()
  var state: AuditState

  for path in dbFiles(root / "db"):
    auditFile(state, schema, path, false)
  for packet in packetFiles(root / "digs"):
    auditFile(state, schema, packet.path, true)

  writeMissingReport(root, report, state.missing)

  echo &"documents={state.documents} missing_sources={state.missing.len} malformed_sources={state.malformedSources} report={relativePath(report, root)}"
  for error in state.errors:
    stderr.writeLine("ERROR: " & error)

  if state.errors.len > 0:
    stderr.writeLine(&"VALIDATION: FAIL ({state.errors.len} error(s))")
    return 1
  if requireSources and state.missing.len > 0:
    stderr.writeLine(&"VALIDATION: FAIL ({state.missing.len} document(s) lack sources; see {report})")
    return 1

  echo "VALIDATION: PASS"
  0


when isMainModule:
  quit(main())
